export const TOGGLE_TO_BE_ADMIN = 'TOGGLE_TO_BE_ADMIN';
export const UPDATE_NICK_NAME = 'UPDATE_NICK_NAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const RESET = 'RESET';

export const SET_HEADER_ELEMTNT = 'SET_HEADER_ELEMTNT';
export const CHECK_USER_OUTH = 'CHECK_USER_OUTH';